apiVersion: v1
kind: Pod
metadata:
  name: busybox-pvc
  labels:
    app: busybox
spec:
  containers:
  - name: busybox1
    image: latelee/busybox
    imagePullPolicy: IfNotPresent
    command: ["sh", "-c", "sleep 3600"]
    volumeMounts:
    - mountPath: /test111
      name: host-volume
  volumes:
  - name: host-volume
    persistentVolumeClaim:
      claimName: nfs-pvc2
