apiVersion: v1
kind: ReplicationController
metadata:
  name: busybox
  labels:
    name: busybox
spec:
  replicas: 2
  selector:
    name: busybox
  template:
    metadata:
      labels:
        name: busybox
    spec:
      containers:
      - name: busybox
        image: latelee/busybox
        imagePullPolicy: IfNotPresent
        command:
        - sleep
        - "3600"

