---  
apiVersion: v1  
kind: ReplicationController  
metadata:  
  name: httpd-rc
spec:  
  replicas: 2
  selector:  
    app: httpd-rc 
  template:   
    metadata:  
      labels:  
        app: httpd-rc
    spec:  
      containers:  
      - name: httpd-rc 
        image: latelee/lidch  
        ports:  
        - containerPort: 80 
