apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wordpress
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress 
    spec:
      containers:
      - name: wordpress
        image: wordpress
        imagePullPolicy: IfNotPresent
        env:
          - name: WORDPRESS_DB_HOST
            value: "127.0.0.1"
          - name: WORDPRESS_DB_USER
            value: "root"
          - name: WORDPRESS_DB_PASSWORD
            value: "password"
      - name: mysql
        imagePullPolicy: IfNotPresent
        image: mysql:5.7
        env:
          - name: MYSQL_ROOT_PASSWORD 
            value: "password"
          - name: MYSQL_DATABASE
            value: "wordpress"
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc 
  labels:
    app: wordpress
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: wordpress
  type: NodePort 

