apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - name: busybox
    image: latelee/busybox
    imagePullPolicy: IfNotPresent
    command: [ "/bin/sh", "-c", "sleep 3600" ]
    env:
      - name: SPECIAL_WHO
        valueFrom:
          configMapKeyRef:
            # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
            name: my-cm
            # Specify the key associated with the value
            key: who
      - name: SPECIAL_NUM
        valueFrom:
          configMapKeyRef:
            name: my-cm
            key: how.many
      - name: SPECIAL_HOW
        valueFrom:
          configMapKeyRef:
            name: special-config
            key: special.how
